apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mycluster
  region: us-east-1

nodeGroups:
  - name: mynodes
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    amiFamily: AmazonLinux2
    ssh:
      allow: true
